# Generated by Django 5.2.6 on 2025-09-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_alter_role_name'), ('users', '0003_remove_user_roles_user_role'), ('users', '0004_delete_role_alter_user_role'), ('users', '0005_user_verification_token_and_more'), ('users', '0006_alter_user_verification_token_and_more'), ('users', '0007_alter_user_verification_token'), ('users', '0008_alter_user_options_alter_user_role_and_more'), ('users', '0009_alter_user_managers_remove_user_first_name_and_more'), ('users', '0010_alter_user_role')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(default='unverified', max_length=20)),
                ('verification_token', models.UUIDField(default=None, editable=False, null=True, unique=True)),
                ('verification_token_created', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('role', 'unverified'), ('role', 'verified'), ('role', 'admin'), ('role', 'superadmin'), _connector='OR'), name='role_valid_values')],
            },
        ),
    ]
